const express = require("express");
const connect = require("./configs/db");
const cors = require("cors");
const testController = require("./controllers/test.controller");
const userController = require("./controllers/user.controller");
const carsController = require("./controllers/car.controller");
const checkoutController = require("./controllers/checkout.controller");
const popularpointsController = require("./controllers/popularpoints.controller");
const bookingdetailController = require("./controllers/bookingdetail.controller");
const popularcityController = require("./controllers/popularcity.controller");
const othercityController = require("./controllers/othercity.controller");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/tests", testController);
app.use(cors());
app.use("/users", userController);
app.use(cors());
app.use("/cars", carsController);
app.use(cors());
app.use("/checkout", checkoutController);
app.use(cors());
app.use("/popularpoints", popularpointsController);
app.use(cors());
app.use("/details", bookingdetailController);
app.use(cors());
app.use("/popularcity", popularcityController);
app.use(cors());
app.use("/othercity", othercityController);

app.listen(4321, async () => {
  await connect();
  console.log("Listening on port 4321");
});
